#:kivy 1.1.1

<varylayout>:
    name:'varylayout'
    background_color: 0.4, 0.6, 0.8, 1
    color: 0, 0, 0, 1
    BoxLayout:
        id: main_layout
        orientation: 'vertical'
        background_color: 0.4, 0.6, 0.8, 1
        color: 0, 0, 0, 1
        TabbedPanel:
            tab_width: self.size[0]/len(self.tab_list)
            tab_height: 130
            do_default_tab: False
            background_color: 0.4, 0.6, 0.8, 1

            TabbedPanelItem:

                text: 'Diversify'
                font_name: 'Quicksand'
                color: (0.5, 0.6, 1, 1.0)   
                background_color: 0.4, 0.6, 0.8, 1  

                BoxLayout:
                    orientation: 'vertical'
                    background_color: 0.1, 0.3, 0.3, 10
                    ScrollView:
                        BoxLayout:
                            id: devicesdiversify
                            orientation: 'vertical'
                            size_hint_y: None
                            height: self.minimum_height
                            GridLayout:
                                size_hint_y: None
                                height: 190
                                cols:1
                                Label:
                                    font_name: 'Quicksand'
                                    underline: True
                                    text:"Diversify WIP\nstable release?, enjoy\nDiversify Scanner, scroll to bottom"
                                    id:diversifytext
                                    bold: True

                                    color: (0.7, 0.3, 0.5, 0.7)


#                                ScrollView:
#                                    BoxLayout:
#                                        padding: 30
#                                        height: 240
#                                        orientation: 'vertical'
#                                        size_hint_y: None
#                                        height: self.minimum_height

                            # 'webhandler': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Open website"
                                    on_release:app.diversifywebhandler()
                                TextInput:
                                    hint_text: "Enter the url of the website you wish"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifywebhandler
                                    multinline:True

                            # 'runcmd': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Run with UAC"
                                    on_release:app.diversifyprogramvl2()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Run without UAC"
                                    on_release:app.diversifyruncmd()
                                TextInput:
                                    hint_text: "Enter the command"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyruncmd
                                    multinline:True

 
                            # 'typestringwithhumandelay': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Type a String like a human"
                                    on_release:app.diversifytypestringwithhumandelay()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text: "Enter the text to enter with a delay between each keystroke"
                                    id:diversifytypestringwithhumandelay
                                    multinline:True

                            # 'setvolume': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Set the volume"
                                    on_release:app.diversifysetvolume()
                                TextInput:
                                    hint_text: "In percentage, 0 - 100"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifysetvolume
                                    multinline:True

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Make the screen rotate"
                                    on_release:app.diversifymakethescreendorotations()
                                TextInput:
                                    hint_text: "For how long to do the rotations? (seconds)"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifymakethescreendorotations
                                    multinline:True



                            # 'inviscurr': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Send to background highlight"
                                    on_release:app.diversifyinviscurr()
                                TextInput:
                                    hint_text: "The app that is focused(windows), will be sent to the background; in seconds"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyinviscurr
                                    multinline:True

 

                            # maximizeprocessvianame
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols: 3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text: "Maximize Process"
                                    on_release: app.diversifymaximizeprocessvianame()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text: "Minimize Process"
                                    on_release: app.diversifyminimizeprocessvianame()
                                TextInput:
                                    hint_text: "Enter exe name"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifychangeapperanjceprocessvianame
                                    multiline: True


                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Always on top"
                                    on_release:app.diversifyalwaysontop()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Unset Always on top"
                                    on_release:app.diversifyunsetalwaysontop()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text: "Enter exe name"
                                    id:diversifyalwaysontop
                                    multinline:True

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Turn the Screen black"
                                    on_release:app.diversifyblackenscreen()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text: "For how will it be black? Duration in seconds"
                                    id:diversifyblackenscreen
                                    multinline:True
   # 'prockill': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Kill a process"
                                    on_release:app.diversifyprockill()
                                TextInput:
                                    hint_text: "Enter exe name"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyprockill
                                    multinline:True

 

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Hide a process"
                                    on_release:app.diversifyhideprocessvianame()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Foreground a process\nfrom the background"
                                    on_release:app.diversifyshowprocessvianame()
                                TextInput:
                                    hint_text: "Enter exe name"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyshowprocessvianame
                                    multinline:True


                            # 'texttospeech': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Speak in\nany language"
                                    on_release:app.diversifyspeakxlanguage()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Windows TTS"
                                    on_release:app.diversifytexttospeech()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifytexttospeech
                                    multinline:True

 

                            # dvdtimeout
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols: 2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text: "Set DVD Timeout\n(0 to disable)" 
                                    on_release: app.diversifydvdtimeout()
                                TextInput:
                                    hint_text: "Enter timeout in seconds"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifydvdtimeout
                                    multiline: True

                            # playytvidbetweentime
                            GridLayout:
                                size_hint_y: None
                                height: 180 
                                cols: 2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text: "Play YouTube Video\nBackground"
                                    on_release: app.diversifyplayytvidbetweentime()
                                TextInput:
                                    hint_text: "Enter the YouTube video URL"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifyplayytvidbetweentimeurl
                                    multiline: True
                            GridLayout: 
                                size_hint_y: None
                                height: 100
                                cols: 2
                                TextInput:
                                    hint_text: "Vid Start Time, in seconds (optional)"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifyplayytvidbetweentimestarttime
                                    multiline: True 
                                TextInput:
                                    hint_text: "Vid End Time, in seconds (optional)"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifyplayytvidbetweentimeendtime
                                    multiline: True

                            GridLayout:
                                size_hint_y: None
                                height: 10
                                background_color: 0.1, 0.3, 0.3, 10
                                cols:1
                                Label:
                                    underline: True
                                    font_name: 'Quicksand'
                                    text:""
                                    bold: True
                                    color: (0.7, 0.1, 0.1, 0.7)
                            
                            # playytvidbetweentimefullscreen
                            GridLayout:
                                size_hint_y: None
                                height: 180
                                cols: 2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text: "Play YouTube Video\nFullscreen"
                                    on_release: app.diversifyplayytvidbetweentimefullscreen()
                                TextInput:
                                    hint_text: "Enter the YouTube video URL"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifyplayytvidbetweentimeurlfullscreen
                                    multiline: True
                            GridLayout:
                                size_hint_y: None
                                height: 100
                                cols: 2
                                TextInput:
                                    hint_text: "Vid Start Time, in seconds (optional)"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifyplayytvidbetweentimestarttimefullscreen
                                    multiline: True
                                TextInput:
                                    hint_text: "Vid End Time, in seconds (optional)"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id: diversifyplayytvidbetweentimeendtimefullscreen
                                    multiline: True
                                


                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Flip screen: normal"
                                    on_release:app.diversifyscreenlandscape()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Flip screen: upsidedown"
                                    on_release:app.diversifyscreenflipped()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Flip screen: right"
                                    on_release:app.diversifyscreenportraitflipped()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Flip screen: left"
                                    on_release:app.diversifyscreenportrait()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Per click,\nlag windows(Enable)"
                                    on_release:app.diversifywindowslagclicksoundenable()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Per click,\nlag windows(Disable)"
                                    on_release:app.diversifywindowslagclicksounddisable()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Swap RMB and LMB"
                                    on_release:app.diversifyswappedswaprmbandlmb()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Unswap RMB and LMB"
                                    on_release:app.diversifyunswappedswaprmbandlmb()



                            # 'meandtheboys': False

                            # ... continue in this manner for the rest of the strings ...
                            # 'meandtheboys': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Me and the boys!"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifymeandtheboys()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Download And Install Chrome"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyinstallchrome()
                            # 'terminateunknownprocesses': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Terminate unknown processes"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyterminateunknownprocesses()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Freeze unknown processes"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.freeze_unknown_processes()

                            # 'terminateunknownprocesses': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable auto termination"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenableterminateunknownprocesses()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable auto termination"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisableterminateunknownprocesses()



                            # 'freezeallprocesses': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Freeze all processes"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyfreezeallprocesses()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Unfreeze all the processes"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyunfreezeallprocesses()


     
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    text:"Payload 1"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    on_release:app.diversifypayload_1()
                                Button:
                                    font_name: 'Quicksand'
                                    text:"Payload 2"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    on_release:app.diversifypayload_2()
                                Button:
                                    font_name: 'Quicksand'
                                    text:"Payload 3"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    on_release:app.diversifypayload_3()
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    text:"Payload 4"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    on_release:app.diversifypayload_4()
                                Button:
                                    font_name: 'Quicksand'
                                    text:"Payload 5"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    on_release:app.diversifypayload_5()
                                Button:
                                    font_name: 'Quicksand'
                                    text:"Payload 6"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    on_release:app.diversifypayload_6()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Hide self"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyhideselfexecutable()

                            # 'restartexplorer': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Restart Explorer"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyrestartexplorer()

                                                        # ... continue this pattern for all strings ...
                            # 'windowslagclicksound': True



                         
                            # ... continue this pattern for all strings ...

                          

                            # ... continue this pattern for all strings ...





                            # 'webhandler': True

                            # ... continue in this manner for the rest of the strings ...



                            # 'playtone': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Play tone"
                                    on_release:app.diversifyplaytone()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text: "What is the frequency?(hz)"
                                    id:diversifyplaytonehz
                                    multinline:True
                                TextInput:
                                    hint_text: "For how long, in milliseconds"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyplaytoneduration
                                    multinline:True

                            # 'playshepardtone': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Initialize Shepard Tone"
                                    on_release:app.diversifyplayshepardtone()
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text: "Start frequency(hz)"
                                    id:diversifyplayshepardtonestarthz
                                    multinline:True
                                TextInput:
                                    hint_text: "End frequency(hz)"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyplayshepardtoneendhz
                                    multinline:True
                                TextInput:
                                    hint_text: "For how long(in seconds)"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyplayshepardtoneduration
                                    multinline:True


                            # 'disablefirewall': False

                    

                            # 'enablemouse': False

                            # ... continue in this manner for the rest of the strings ...
                            # 'enablemouse': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable mouse"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenablemouse()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable mouse"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisablemouse()

                            # 'enablekeyboard': False

                            # ... continue in this manner for the rest of the strings ...
                            # 'enablekeyboard': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable keyboard"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenablekeyboard()

                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable Keyboard"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisablekeyboard()

                            # 'presskeys': True

                            # ... continue in this manner for the rest of the strings ...
                            # 'presskeys': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Press keys"
                                    on_release:app.diversifypresskeys()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifypresskeys
                                    multinline:True

                            # 'writetext': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Write text"
                                    on_release:app.diversifywritetext()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifywritetext
                                    multinline:True

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text:"Override the subnet, e.g. '192.168.1.'"
                                    id:overridensubnetdiversify
                                    multinline:True
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Toggle school subnets\n(Status: Disabled)" 
                                    background_color: (0.8, 0.2, 0.7, 1)
                                    color: (0.2, 0.6, 1, 1)
                                    bold:True
                                    on_press: app.diverisfy_subnet_ofschlang(self)


                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Run a full scan for diversified hosts\n - This Will take a while to complete"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.scan_for_hosts()




 

            TabbedPanelItem:
                text: 'Diversify Tools'
                font_name: 'Quicksand'
                color: (0.5, 0.6, 1, 1.0)   
                background_color: 0.4, 0.6, 0.8, 1  
                #on_release: app.show_password_prompt() if not app.is_tools_unlocked else None

                BoxLayout:
                    orientation: 'vertical'
                    background_color: 0.1, 0.3, 0.3, 10
                    ScrollView:
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_y: None
                            height: self.minimum_height
                            # self_destruct
                            GridLayout:
                                size_hint_y: None
                                height: 60
                                cols: 1
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.8, 0.2, 0.2, 0.6  # Reddish background
                                    on_press: self.color = (1, 0.5, 0.5, 0.8)  # Lighter red on press
                                    on_release: self.color = (1, 0.5, 0.5, 1)
                                    color: 1, 0.5, 0.5, 1
                                    bold: True
                                    text: "Self Destruct"
                                    on_release: app.diversifyself_destruct()
                                    
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Label:
                                    underline: True
                                    font_name: 'Quicksand'
                                    text:"Diversify Tools WIP"
                                    bold: True
                                    color: (0.7, 0.1, 0.1, 0.7)
                            # 'disableuseraccountcontrol': False

    

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.87, 0.4, 0.6, 1
                                    color: 0.5, 0.8, 1, 0.8
                                    bold: True
                                    text:"Send priority ipv4\nto selected host"
                                    on_release:app.ipv4prioritize()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text: "Default: send this device’s IPv4; else: overwrite it."
                                    id:ipv4prioritize
                                    multinline:True

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.87, 0.4, 0.6, 1
                                    color: 0.5, 0.8, 1, 0.8
                                    bold: True
                                    text:"Clear host priorities"
                                    on_release:app.clearprioritize()
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.7, 0.4, 0.6, 1
                                    color: 0.9, 0.8, 1, 0.8
                                    bold: True
                                    text:"Dismantle Windows"
                                    on_release:app.nuke_all_hives()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Send all hosts a Todo"
                                    on_release:app.diversifysendallhostsatodo()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifysendallhostsatodo
                                    multinline:True
                            # 'runpythonscript': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Remote run python code"
                                    on_release:app.diversifyrunpythonscript()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    hint_text: "Plain text python - as a script"
                                    id:diversifyrunpythonscript
                                    multinline:True



                            # 'runpythonscript': True


     # ... continue this pattern for all strings ...
                            # 'updateselfvialink': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Update self via a link"
                                    on_release:app.diversifyupdateselfvialink()
                                TextInput:
                                    hint_text: "Make sure that the link is a direct download, use dropbox, at the end, dl=1"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyupdateselfvialink
                                    multinline:True

                            # 'renameself': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Make the app rename itself"
                                    on_release:app.diversifyrenameself()
                                TextInput:
                                    hint_text: "Set a new name!, you don't have to enter the .exe at the end(preferably don't)" 
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifyrenameself
                                    multinline:True
  # 'restartself': False


                            # 'movetofolder': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Change the app directory"
                                    on_release:app.diversifymovetofolder()
                                TextInput:
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifymovetofolder
                                    multinline:True



                            # 'dosipport': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Disable remotes DOS\nIPv4 isn't accounted"
                                    on_release:app.diversifyclosedosipport()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Send a DOS\n to an IP"
                                    on_release:app.diversifydosipport()
                                TextInput:
                                    hint_text:"Enter the ip and the port, formatted as IP:PORT"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:diversifydosipport
                                    multinline:True


                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Block application\nby name"
                                    on_release:app.block_application_by_name()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Unblock application\nby name"
                                    on_release:app.unblock_application_by_name()
                                TextInput:
                                    hint_text:"Enter exe name"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:unblock_application_by_name
                                    multinline:True
 

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:3
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Block ports\nfor application"
                                    on_release:app.block_ports_for_application()
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Unblock ports\nfor application"
                                    on_release:app.unblock_ports_for_application()
                                TextInput:
                                    hint_text:"Enter exe name"
                                    background_color: 0.1, 0.3, 0.3, 10
                                    bold: True
                                    id:unblock_ports_for_application
                                    multinline:True





                            # 'killself': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Kill diversify's process"
                                    on_release:app.diversifykillself()
   
                            # 'killself': True
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Bypass Firewall"
                                    on_release:app.bypassfirewall()

                            # 'handletostartsequences': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Run startup sequence(manual or args 'initialize')"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyhandletostartsequences()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Reboot Windows"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyrestartsystem()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Restart diversify"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyrestartself()
                            # 'resetnetwork': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Reset network"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyresetnetwork()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text:"Reset Firewall"
                                    on_release:app.reset_firewall


                            # 'restarttoadvancedoptions': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Restart to advanced options"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyrestarttoadvancedoptions()
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Restart and request UAC permission\nif declined process needs to be reopened manually"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyrestarttouac()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Add self to Safemode"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyaddselftosafemode()

                            # 'protectfileself': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Protect own file, permission-wise"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyprotectfileself()

                            # unprotectselffile
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols: 1
                                Button:
                                    font_name: 'Quicksand'
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold: True
                                    text: "Unprotect Self File"
                                    on_release: app.diversifyunprotectselffile()


                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Corrupt Task manager"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifycorrupttaskmgr()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Corrupt Task Scheduler"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.corrupt_taskscheduler()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Corrupt MMC"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifycorruptmmc()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Corrupt Regedit"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifycorruptregedit()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Corrupt dllhost"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifycorruptdllhost()
                            
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Corrupt sfc"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifycorruptsfc()

                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:1
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Corrupt systemreset"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifycorruptsystemreset()

                            # 'disablewindowsdefender': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable Defender"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenablewindowsdefender()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable Defender"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisablewindowsdefender()

                            # 'enableuwf': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable UWF"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenableuwf()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable UWF"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisableuwf()
        
                            # 'disableresetoptions': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable Reset Options"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenableresetoptions()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable Reset Options"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisableresetoptions()
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable UAC"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenableuseraccountcontrol()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable UAC"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisableuseraccountcontrol()

                            # 'disablefirewall': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enabel Firewall"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenablefirewall()

                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable Firewall"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisablefirewall()
                            # 'offsmartassnointernet': False

                            # 'getscriptdirectory': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Get the script directory"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifygetscriptdirectory()

                                Button:
                                    font_name: 'Quicksand'
                                    text: "Get the script filename"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifygetscriptfilename()
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable Internet handling"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyonsmartassnointernet()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable Internet handling"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyoffsmartassnointernet()


                            # 'disabletaskmgr': False

                            # ... continue in this manner for the rest of the strings ...
                            # 'disabletaskmgr': False
                            GridLayout:
                                size_hint_y: None
                                height: 160
                                cols:2
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Enable taskmgr"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifyenabletaskmgr()
                                Button:
                                    font_name: 'Quicksand'
                                    text: "Disable taskmgr"
                                    background_color: 0.6, 0.8, 1, 1
                                    on_press: self.color = (0.5, 0.8, 1, 0.8)
                                    on_release: self.color = ((0.9, 0.9, 0.94, 1))
                                    color: (0.9, 0.9, 0.94, 1)
                                    bold:True
                                    on_press: app.diversifydisabletaskmgr()

